### ISSUE TITLE
dependencies confict

### ISSUE THREAD

**Issue by invisible30** [1zhou-Wang/MemVR#11]
```
llava 1.2.2.post1 requires transformers==4.37.2, but you have transformers 4.40.0 which is incompatible.
```

**Comment by 1zhou-Wang** [comment]
Hi,

Thank you for your feedback. You may refer to the [Installation](https://github.com/1zhou-Wang/MemVR?tab=readme-ov-file#installation)  section, where we recommend you to 1. set up the environment of [LLaVA](https://github.com/haotian-liu/LLaVA) 2. update the _transformers_ lib to 4.40.0. Don't worry about the warning, everything works fine here. 

The reason not using the default version as LLaVA does is that we want to simplify the re-producing procedure, where we found a version of _transformers_ that is compatible for inferencing all models (LLaVA1.5, LLaVA1.6, LLaVA-NeXT, Qwen-VL-Chat, GLM-4v). So don't worry if there's a warning for incompatible llava 1.2.2.post1. 

Do let us know if you have any other concern!

Yizhou

**Comment by invisible30** [comment]
when I upgrade to 4.40.0, I got the problem 
```
TypeError: LlavaLlamaForCausalLM.forward() got an unexpected keyword argument 'cache_position'
```

**Comment by 1zhou-Wang** [comment]
> when I upgrade to 4.40.0, I got the problem
> 
> ```
> TypeError: LlavaLlamaForCausalLM.forward() got an unexpected keyword argument 'cache_position'
> ```

Hi,

This is caused by the change of transformers lib. Please refer to this post [TypeError: LlavaLlamaForCausalLM.forward() got an unexpected keyword argument 'cache_position'](https://github.com/huggingface/transformers/issues/29426#issuecomment-1979499925). Or you may manually add_cache_position=None_ to [llava_llama.py](https://github.com/haotian-liu/LLaVA/blob/main/llava/model/language_model/llava_llama.py) at line 70.

Furthermore, we have updated _readme.md_ for detailed instructions on how to setup the environment of MemVR. Thanks for your kind feedback!

Please do let us know if you have any questions!

Yizhou
